server:
  port: 8883
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.125.177:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    password: Liuyong123!
    username: root
  application:
    name: zuul
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
zuul:
  routes:
    api-service1:
      path: /api-service1/**
      serviceId: service1
    api-service2:
      path: /api-service2/**
      serviceId: service2
