server:
  port: 8882
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.125.177:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    password: Liuyong123!
    username: root
  application:
    name: service2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
