server:
  port: 8881
spring:
  application:
    name: service1
  profiles:
    active: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
feign:
  hystrix:
    enabled: true
jasypt:
  encryptor:
    password: ly
debug: true
logging:
  config: classpath:logback.xml
logging.level.org.springframework.boot.autoconfigure: ERROR