spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.125.177:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    password: ENC(eVd66ztaC/coa/anuF/J4uVBV/KMJS/E)
    username: root
  rabbitmq:
    host: 47.112.125.177
    port: 5672
    username: admin
    password: 123456